Traceback (most recent call last):

  File "d:\projects\Data_Science_and_Co_TU_Wien\BA\scripts\trainUrbanCV.py", line 470, in <module>
    cv_results = run_cross_validation()

  File "d:\projects\Data_Science_and_Co_TU_Wien\BA\scripts\trainUrbanCV.py", line 427, in run_cross_validation
    fold_results = train_fold(
        fold=fold,
    ...<10 lines>...
        use_validation=use_validation
    )

  File "d:\projects\Data_Science_and_Co_TU_Wien\BA\scripts\trainUrbanCV.py", line 332, in train_fold
    train_loss, train_acc, sub_epoch_info = train_one_epoch(
                                            ~~~~~~~~~~~~~~~^
        model, criterion, optimizer, train_loader,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        regularize=True, scheduler=scheduler,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        sub_epoch_documentation=10, augments_use=augments
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^

  File "d:\projects\Data_Science_and_Co_TU_Wien\BA\efficientSsmLukin\utils.py", line 51, in train_one_epoch
    for i, (inputs, labels) in pbar:
           ^^^^^^^^^^^^^^^^

ValueError: too many values to unpack (expected 2)

